version: '3'
services:
  bestbuy_rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5681:5672
      - 15681:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - bestbuy
  
  eureka_server:
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - bestbuy

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8101:8080
    links:
      - eureka_server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka_server:8761/eureka
    networks:
      - bestbuy

networks:
  bestbuy:
    name: bestbuy
