version: '3'
services:
  bestbuy_rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5681:5672
      - 15681:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - bestbuy

  # bestbuy_nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8102:80
  #   networks:
  #     - bestbuy

networks:
  bestbuy:
    name: bestbuy
