version: '3'
services:
  authentication_redis:
    image: redis:latest
    ports:
      - 6379:6379

  authentication_postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication

  authentication_rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5671:5672
      - 15671:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro


  authentication_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      - authentication_postgres
      - authentication_redis
      - authentication_rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://authentication_postgres:5432/authentication
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: authentication_redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: authentication_rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
