apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-postgres
  template:
    metadata:
      labels:
        app: authentication-postgres
    spec:
      containers:
      - name: authentication-postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: authentication
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-postgres
spec:
  selector:
    app: authentication-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP