apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-redis
  template:
    metadata:
      labels:
        app: authentication-redis
    spec:
      containers:
      - name: authentication-redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-redis
spec:
  selector:
    app: authentication-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP