apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reviews-mongodb
  name: reviews-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reviews-mongodb
    spec:
      containers:
        - image: mongo:4.4.14-rc0-focal
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: reviews-mongodb-claim0
      restartPolicy: Always
      volumes:
        - name: reviews-mongodb-claim0
          persistentVolumeClaim:
            claimName: reviews-mongodb-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reviews-mongodb
  name: reviews-mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: reviews-mongodb-claim0
  name: reviews-mongodb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}