apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-postgres
  name: user-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: best_buy
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:latest
          name: user-postgres
          ports:
            - containerPort: 5432 
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-authentication-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-authentication-claim0
          persistentVolumeClaim:
            claimName: postgres-authentication-claim0

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-postgres
  name: user-postgres
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
  selector:
    app: user-postgres
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: user-postgres-claim0
  name: user-postgres-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
