apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-app
          image: moeshiba/productsapp-products_app
          ports:
            - containerPort: 9099
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://products-mongodb.default.svc.cluster.local:27017/products
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_HOST
              value: products-redis
            - name: SPRING_RABBITMQ_HOST
              value: bestbuy-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5681"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-redis
  template:
    metadata:
      labels:
        app: products-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: products-redis
spec:
  selector:
    app: products-redis
  ports:
    - protocol: TCP
      port: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: products-app
spec:
  # type: LoadBalancer
  selector:
    app: products-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 9099
