apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-app
  template:
    metadata:
      labels:
        app: transactions-app
    spec:
      containers:
        - name: transactions-app
          image: moeshiba/transactionapp-transactions_app
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://transactions-postgres:5432/transactions
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATA_REDIS_HOST
              value: transactions-redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_RABBITMQ_HOST
              value: bestbuy-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-redis
  template:
    metadata:
      labels:
        app: transactions-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: transactions-app
spec:
  selector:
    app: transactions-app
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-redis
spec:
  selector:
    app: transactions-redis
  ports:
    - protocol: TCP
      port: 6384
      targetPort: 6379
      
