version: '3'
services:
  transactions_redis:
    image: redis:latest
    ports:
      - 6379:6379

  transactions_postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions

  transactions_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    depends_on:
      - transactions_postgres
      - transactions_redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transactions_postgres:5432/transactions
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: transactions_redis
      SPRING_DATA_REDIS_PORT: 6379
