version: '3'
services:
  user_postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5443:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: best_buy
    networks:
      - bestbuy

  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8086:8080
    depends_on:
      - user_postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user_postgres:5432/best_buy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - bestbuy

networks:
  bestbuy:
    name: bestbuy
    external: true
